version: '3'

services:
  app:
    build: .
    command: mix do ecto.create, phx.server
    environment:
      # Interpolated env vars should be defined in a .env file
      MIX_ENV: dev
      PG_USER: 
      PG_PASS:
      PG_HOST:
      YOUTRACK_API_TOKEN:
    ports:
      - 4000:4000
    volumes:
      - .:/app
